language: c
dist: xenial
script:
 - cd toolchain && tar xpf x86.tar.bz2 && cd ..
 - ARCH=x86 SUBARCH=32 make
 - ARCH=x86 SUBARCH=64 make
before_install:
 - sudo apt-get -qq update && sudo apt-get install -y build-essential bison flex libgmp3-dev libmpc-dev libmpfr-dev texinfo autoconf automake xorriso gnu-efi mtools
 - wget http://mirrors.kernel.org/ubuntu/pool/main/m/mpfr4/libmpfr6_4.0.1-1_amd64.deb -O ~/libmpfr6.deb
 - dpkg -x ~/libmpfr6.deb ~/libmpfr6
 - sudo cp -RT ~/libmpfr6 /
 - wget https://github.com/CHOSTeam/CHicago-Toolchain/releases/download/prebuilt-gcc/x86.tar.bz2 -P toolchain/
